import type { AppProps } from 'next/app';
import Head from 'next/head';
import Navbar from '@/components/molecules/navbar';
import "./app.css";

export default function App({ Component, pageProps }: AppProps) {
  return <>
    <Head>
      <title>Create Next App</title>
      <link rel="icon" href="/logo.png" type="image/png" />
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
    </Head>
    <div className="bg-gray-900 h-[100vh] flex flex-col items-center text-gray-50">
      <div className="fixed top-0 left-0 right-0 border-b">
        <Navbar />
      </div>
      <Component {...pageProps} />
    </div>
  </>;
}
